
import { QuizItem } from '../types';

export const quizData: QuizItem[] = [
  {
    id: 1,
    sentence: 'We need to __ our meeting until next week due to unforeseen circumstances.',
    sentence_pl: 'Musimy przełożyć nasze spotkanie na przyszły tydzień z powodu nieprzewidzianych okoliczności.',
    correctWord: 'postpone',
    options: [
      { word: 'cancel', word_pl: 'anulować', isCorrect: false },
      { word: 'postpone', word_pl: 'przełożyć', isCorrect: true },
      { word: 'attend', word_pl: 'uczestniczyć', isCorrect: false },
      { word: 'schedule', word_pl: 'zaplanować', isCorrect: false },
    ],
  },
  {
    id: 2,
    sentence: 'Could you please __ the key takeaways from the presentation?',
    sentence_pl: 'Czy mógłbyś podsumować kluczowe wnioski z prezentacji?',
    correctWord: 'summarize',
    options: [
      { word: 'summarize', word_pl: 'podsumować', isCorrect: true },
      { word: 'ignore', word_pl: 'ignorować', isCorrect: false },
      { word: 'extend', word_pl: 'przedłużyć', isCorrect: false },
      { word: 'complicate', word_pl: 'komplikować', isCorrect: false },
    ],
  },
  {
    id: 3,
    sentence: 'Our team has to __ a lot of challenges to meet the deadline.',
    sentence_pl: 'Nasz zespół musi sprostać wielu wyzwaniom, aby dotrzymać terminu.',
    correctWord: 'face',
    options: [
      { word: 'avoid', word_pl: 'unikać', isCorrect: false },
      { word: 'create', word_pl: 'tworzyć', isCorrect: false },
      { word: 'face', word_pl: 'sprostać', isCorrect: true },
      { word: 'report', word_pl: 'zgłosić', isCorrect: false },
    ],
  },
  {
    id: 4,
    sentence: "Let's touch __ next week to discuss our progress.",
    sentence_pl: 'Skontaktujmy się w przyszłym tygodniu, aby omówić nasze postępy.',
    correctWord: 'base',
    options: [
      { word: 'base', word_pl: 'się', isCorrect: true },
      { word: 'up', word_pl: 'się', isCorrect: false },
      { word: 'on', word_pl: 'się', isCorrect: false },
      { word: 'in', word_pl: 'się', isCorrect: false },
    ],
  },
  {
    id: 5,
    sentence: 'To increase profits, we need to cut __ on unnecessary expenses.',
    sentence_pl: 'Aby zwiększyć zyski, musimy ograniczyć niepotrzebne wydatki.',
    correctWord: 'down',
    options: [
      { word: 'off', word_pl: 'odciąć', isCorrect: false },
      { word: 'out', word_pl: 'wyciąć', isCorrect: false },
      { word: 'through', word_pl: 'przeciąć', isCorrect: false },
      { word: 'down', word_pl: 'ograniczyć', isCorrect: true },
    ],
  },
  {
    id: 6,
    sentence: 'He is responsible for drawing __ the new project proposal.',
    sentence_pl: 'On jest odpowiedzialny za sporządzenie nowej propozycji projektu.',
    correctWord: 'up',
    options: [
      { word: 'up', word_pl: 'sporządzić', isCorrect: true },
      { word: 'in', word_pl: 'wciągnąć', isCorrect: false },
      { word: 'out', word_pl: 'wyciągnąć', isCorrect: false },
      { word: 'on', word_pl: 'narysować na', isCorrect: false },
    ],
  },
  {
    id: 7,
    sentence: 'We need to get the ball __ on this marketing campaign.',
    sentence_pl: 'Musimy rozpocząć tę kampanię marketingową.',
    correctWord: 'rolling',
    options: [
      { word: 'jumping', word_pl: 'skaczącą', isCorrect: false },
      { word: 'rolling', word_pl: 'toczącą się', isCorrect: true },
      { word: 'stopping', word_pl: 'zatrzymującą się', isCorrect: false },
      { word: 'flying', word_pl: 'latającą', isCorrect: false },
    ],
  },
  {
    id: 8,
    sentence: 'I think we are all on the same __ regarding the next steps.',
    sentence_pl: 'Myślę, że wszyscy zgadzamy się co do następnych kroków.',
    correctWord: 'page',
    options: [
      { word: 'book', word_pl: 'książce', isCorrect: false },
      { word: 'chapter', word_pl: 'rozdziale', isCorrect: false },
      { word: 'page', word_pl: 'stronie', isCorrect: true },
      { word: 'line', word_pl: 'linii', isCorrect: false },
    ],
  },
  {
    id: 9,
    sentence: 'The new software allows us to __ our workflow significantly.',
    sentence_pl: 'Nowe oprogramowanie pozwala nam znacznie usprawnić przepływ pracy.',
    correctWord: 'streamline',
    options: [
      { word: 'complicate', word_pl: 'komplikować', isCorrect: false },
      { word: 'streamline', word_pl: 'usprawnić', isCorrect: true },
      { word: 'delay', word_pl: 'opóźnić', isCorrect: false },
      { word: 'widen', word_pl: 'poszerzyć', isCorrect: false },
    ],
  },
  {
    id: 10,
    sentence: 'The company decided to __ its operations to Asia.',
    sentence_pl: 'Firma zdecydowała się rozszerzyć swoją działalność na Azję.',
    correctWord: 'expand',
    options: [
      { word: 'reduce', word_pl: 'zmniejszyć', isCorrect: false },
      { word: 'maintain', word_pl: 'utrzymać', isCorrect: false },
      { word: 'expand', word_pl: 'rozszerzyć', isCorrect: true },
      { word: 'sell', word_pl: 'sprzedać', isCorrect: false },
    ],
  },
    {
    id: 11,
    sentence: 'Could you please follow __ on that email I sent last week?',
    sentence_pl: 'Czy mógłbyś proszę nawiązać do maila, którego wysłałem w zeszłym tygodniu?',
    correctWord: 'up',
    options: [
      { word: 'on', word_pl: 'na', isCorrect: false },
      { word: 'with', word_pl: 'z', isCorrect: false },
      { word: 'up', word_pl: 'nawiązać', isCorrect: true },
      { word: 'in', word_pl: 'w', isCorrect: false },
    ],
  },
  {
    id: 12,
    sentence: 'We need to think outside the __ to solve this complex problem.',
    sentence_pl: 'Musimy myśleć nieszablonowo, aby rozwiązać ten złożony problem.',
    correctWord: 'box',
    options: [
      { word: 'circle', word_pl: 'koła', isCorrect: false },
      { word: 'box', word_pl: 'pudełka', isCorrect: true },
      { word: 'square', word_pl: 'kwadratu', isCorrect: false },
      { word: 'lines', word_pl: 'linii', isCorrect: false },
    ],
  },
  {
    id: 13,
    sentence: 'Our main __ for this quarter is to increase user engagement by 20%.',
    sentence_pl: 'Naszym głównym celem na ten kwartał jest zwiększenie zaangażowania użytkowników o 20%.',
    correctWord: 'objective',
    options: [
      { word: 'objective', word_pl: 'cel', isCorrect: true },
      { word: 'failure', word_pl: 'porażka', isCorrect: false },
      { word: 'distraction', word_pl: 'rozproszenie', isCorrect: false },
      { word: 'guess', word_pl: 'domysł', isCorrect: false },
    ],
  },
    {
    id: 14,
    sentence: 'She was praised for her ability to __ difficult clients effectively.',
    sentence_pl: 'Została pochwalona za umiejętność skutecznego radzenia sobie z trudnymi klientami.',
    correctWord: 'handle',
    options: [
      { word: 'handle', word_pl: 'radzić sobie z', isCorrect: true },
      { word: 'ignore', word_pl: 'ignorować', isCorrect: false },
      { word: 'create', word_pl: 'tworzyć', isCorrect: false },
      { word: 'invite', word_pl: 'zapraszać', isCorrect: false },
    ],
  },
  {
    id: 15,
    sentence: 'The project was a great success, thanks to the team\'s __ efforts.',
    sentence_pl: 'Projekt odniósł wielki sukces dzięki wspólnym wysiłkom zespołu.',
    correctWord: 'collaborative',
    options: [
      { word: 'separate', word_pl: 'oddzielnym', isCorrect: false },
      { word: 'collaborative', word_pl: 'wspólnym', isCorrect: true },
      { word: 'weak', word_pl: 'słabym', isCorrect: false },
      { word: 'individual', word_pl: 'indywidualnym', isCorrect: false },
    ],
  },
];
